apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: mysql                  ### so here rds mysql database is connected with backend with this end point need to give here


#for mysql server you need to give mysql that it